### ISSUE TITLE
Images not loading in web view

### ISSUE THREAD

**Issue by mperezco** [konveyor/forklift-documentation#186]
When accessing the documentation via web: https://forklift-docs.konveyor.io/documentation/doc-Migration_Toolkit_for_Virtualization/master/index.html

... Images do not load. For example this diagram:
![image](https://user-images.githubusercontent.com/1738510/128320579-f21ae5ee-8a09-4ef6-a700-1486d84cb4be.png)

Which is pointing to this URL:
https://forklift-docs.konveyor.io/documentation/doc-Migration_Toolkit_for_Virtualization/master/modules/images/136_Upstream_Migration_Toolkit_0121_mtv-workflow.svg
... that returns a 404

**Comment by apinnick** [comment]
Thanks. The images directory in the config_yml file was no longer working for upstream builds. I fixed the path and now the images are loading.
